cases:
  dev:
    command: docker compose up -d
  
  recreate:
    command: docker compose up -d --force-recreate
  
  down:
    command: docker compose down
  
  build:
    command: docker compose build
